### ISSUE TITLE
FileNotFoundException when clicking backup button

### ISSUE THREAD

**Issue by alxcyl** [lucidlemon/PraiseTheSave#1]
```
System.IO.FileNotFoundException: Could not load file or assembly 'Ionic.Zip, Version=1.9.8.0, Culture=neutral, PublicKeyToken=6583c7c814667745' or one of its dependencies. The system cannot find the file specified.
File name: 'Ionic.Zip, Version=1.9.8.0, Culture=neutral, PublicKeyToken=6583c7c814667745'
   at PraiseTheSave.Form1.doBackup(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I only have DS1 installed. Windows 10.

**Comment by lucidlemon** [comment]
Ah damn it I didn't link the latest version in the readme, please grab [this release](https://github.com/lucidlemon/PraiseTheSave/releases/tag/1.0.1) which fixes this problem.

**Comment by alxcyl** [comment]
That fixes it.
